### ISSUE TITLE
After post screen, sharing & arweave tx.

### ISSUE THREAD

**Issue by aidanok** [alexreyes/perma-quarantine-notes-web#14]
Leaving out some detail here but, after a person posts a note, we should give them some kind of information screen, with some variation of  

- The arweave transaction id and link to see the 'permafied' note 
- Option to share the post of social platforms

**Comment by alexreyes** [comment]
235ae5a006fbcc427767eeadaadda1b7271b8580

I made a popup that shows on the home page after a user makes a post. It has a transaction viewer link + option to share the site.
