### ISSUE TITLE
Rich text editor that's mobile friendly

### ISSUE THREAD

**Issue by alexreyes** [alexreyes/perma-quarantine-notes-web#6]

**Comment by aidanok** [comment]
My gut feeling here is that this will be hard to find :) 

Mobile browsers, screen sizes etc, are extremely varied, and any kind of complex ui is _really hard_ to get right in them. 

I would say have a look around, there might be something suitable, but a simple textarea still allows people to format text and use emoticons etc and will work everywhere.

**Comment by alexreyes** [comment]
Good point. I think I'll just keep it simple with this one.

**Comment by alexreyes** [comment]
Good point. I think I'll just keep it simple with this one.
